[package]
name = "p9-2024-oort-selfgrav"
version = "0.1.0"
edition = "2021"
description = "Reproduction of Batygin & Nesvorny (2024) 'Self-Gravitational Dynamics Within the Inner Oort Cloud'"

[dependencies]
p9-core = { path = "../p9-core" }
rand = { workspace = true }
rand_distr = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
uom = "0.38.0"
