[package]
name = "p9-2022-iras-candidate"
version = "0.1.0"
edition = "2021"

[dependencies]
p9-core = { path = "../p9-core" }
p9-2025-iras-akari = { path = "../p9-2025-iras-akari" }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
uom = "0.38.0"
